pref("extensions.zotfile.source_dir_ff",true);
pref("extensions.zotfile.source_dir","");
pref("extensions.zotfile.dest_dir", "");
pref("extensions.zotfile.filetypes", "pdf,doc,txt,rtf");
pref("extensions.zotfile.useFileTypes", true);
pref("extensions.zotfile.allFiles", false);
pref("extensions.zotfile.useZoteroToRename", false);
pref("extensions.zotfile.renameFormat", "%a_%y_%t");
pref("extensions.zotfile.renameFormat_patent", "%a_%y_%t"); 
pref("extensions.zotfile.truncate_title", true);
pref("extensions.zotfile.truncate_smart", true);
pref("extensions.zotfile.truncate_title_max", true);
pref("extensions.zotfile.max_titlelength", 80);
pref("extensions.zotfile.truncate_authors", true);
pref("extensions.zotfile.max_authors", 2);
pref("extensions.zotfile.add_etal", true);
pref("extensions.zotfile.etal", " et al");
pref("extensions.zotfile.confirmation", true);     
pref("extensions.zotfile.confirmation_batch_ask", true);     
pref("extensions.zotfile.confirmation_batch", 2);
pref("extensions.zotfile.import", true);
pref("extensions.zotfile.replace_blanks", false);
pref("extensions.zotfile.subfolder", false);
pref("extensions.zotfile.subfolderFormat", "/%w/%y");  
pref("extensions.zotfile.userInput", false);
pref("extensions.zotfile.userInput_Default", "Paper");
pref("extensions.zotfile.version","");

pref("extensions.zotfile.tablet", false);
pref("extensions.zotfile.tablet.dest_dir", "");
pref("extensions.zotfile.tablet.rename", true);
pref("extensions.zotfile.tablet.dest_dir_relativePath", true);
pref("extensions.zotfile.tablet.tag", "_READ");
pref("extensions.zotfile.tablet.tagParentPush", false);
pref("extensions.zotfile.tablet.tagParentPush_tag", "_READ");
pref("extensions.zotfile.tablet.tagParentPull", false);
pref("extensions.zotfile.tablet.tagParentPull_tag", "_ANNOTATED");
pref("extensions.zotfile.tablet.confirmRepush", true);  
pref("extensions.zotfile.tablet.storeCopyOfFile", false);  
pref("extensions.zotfile.tablet.storeCopyOfFile_suffix", "_annotated");  
pref("extensions.zotfile.tablet.projectFolders", 0);  
pref("extensions.zotfile.tablet.projectFolders01", false);
pref("extensions.zotfile.tablet.projectFolders01_folder", "");
pref("extensions.zotfile.tablet.projectFolders01_label", "Project 01");
pref("extensions.zotfile.tablet.projectFolders02", false);
pref("extensions.zotfile.tablet.projectFolders02_folder", "");
pref("extensions.zotfile.tablet.projectFolders02_label", "Project 02");
pref("extensions.zotfile.tablet.projectFolders03", false);
pref("extensions.zotfile.tablet.projectFolders03_folder", "");
pref("extensions.zotfile.tablet.projectFolders03_label", "Project 03");
pref("extensions.zotfile.tablet.projectFolders04", false);
pref("extensions.zotfile.tablet.projectFolders04_folder", "");
pref("extensions.zotfile.tablet.projectFolders04_label", "Project 04");
pref("extensions.zotfile.tablet.projectFolders05", false);
pref("extensions.zotfile.tablet.projectFolders05_folder", "");
pref("extensions.zotfile.tablet.projectFolders05_label", "Project 05");
pref("extensions.zotfile.tablet.projectFolders06", false);
pref("extensions.zotfile.tablet.projectFolders06_folder", "");
pref("extensions.zotfile.tablet.projectFolders06_label", "Project 06");
pref("extensions.zotfile.tablet.projectFolders07", false);
pref("extensions.zotfile.tablet.projectFolders07_folder", "");
pref("extensions.zotfile.tablet.projectFolders07_label", "Project 07");
pref("extensions.zotfile.tablet.projectFolders08", false);
pref("extensions.zotfile.tablet.projectFolders08_folder", "");
pref("extensions.zotfile.tablet.projectFolders08_label", "Project 08");
pref("extensions.zotfile.tablet.projectFolders09", false);
pref("extensions.zotfile.tablet.projectFolders09_folder", "");
pref("extensions.zotfile.tablet.projectFolders09_label", "Project 09");
pref("extensions.zotfile.tablet.projectFolders10", false);
pref("extensions.zotfile.tablet.projectFolders10_folder", "");
pref("extensions.zotfile.tablet.projectFolders10_label", "Project 10");        
pref("extensions.zotfile.tablet.projectFolders11", false);
pref("extensions.zotfile.tablet.projectFolders11_folder", "");
pref("extensions.zotfile.tablet.projectFolders11_label", "Project 11");
pref("extensions.zotfile.tablet.projectFolders12", false);
pref("extensions.zotfile.tablet.projectFolders12_folder", "");
pref("extensions.zotfile.tablet.projectFolders12_label", "Project 12");
pref("extensions.zotfile.tablet.projectFolders13", false);
pref("extensions.zotfile.tablet.projectFolders13_folder", "");
pref("extensions.zotfile.tablet.projectFolders13_label", "Project 13");
pref("extensions.zotfile.tablet.projectFolders14", false);
pref("extensions.zotfile.tablet.projectFolders14_folder", "");
pref("extensions.zotfile.tablet.projectFolders14_label", "Project 14");
pref("extensions.zotfile.tablet.projectFolders15", false);
pref("extensions.zotfile.tablet.projectFolders15_folder", "");
pref("extensions.zotfile.tablet.projectFolders15_label", "Project 15");                       
pref("extensions.zotfile.tablet.subfolder", false);
pref("extensions.zotfile.tablet.subfolderFormat", "/%w/%y");  
pref("extensions.zotfile.tablet.mode", 1);         

pref("extensions.zotfile.pdfExtraction.Pull", true);
pref("extensions.zotfile.pdfExtraction.MenuItem", true);
pref("extensions.zotfile.pdfExtraction.NoteTruePage", true);     
pref("extensions.zotfile.pdfExtraction.NoteFullCite", true);
pref("extensions.zotfile.pdfExtraction.NoteRemoveHyphens", true);                                          
pref("extensions.zotfile.pdfExtraction.NoteHtmlTagStart", "<i>");
pref("extensions.zotfile.pdfExtraction.NoteHtmlTagEnd", "</i>");
pref("extensions.zotfile.pdfExtraction.HighlightHtmlTagStart", "");
pref("extensions.zotfile.pdfExtraction.HighlightHtmlTagEnd", "");
pref("extensions.zotfile.pdfExtraction.UnderlineHtmlTagStart", "<u>");
pref("extensions.zotfile.pdfExtraction.UnderlineHtmlTagEnd", "</u>");
